-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- vim.api.nvim_create_autocmd("LspAttach", {
--   callback = function(args)
--     if vim.bo[args.buf].filetype ~= "java" then
--       return
--     end
--
--     vim.schedule(function()
--       if vim.api.nvim_buf_is_valid(args.buf) then
--         vim.lsp.inlay_hint.enable(false, {
--           bufnr = args.buf,
--         })
--       end
--     end)
--   end,
-- })
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*.java",
--   callback = function()
--     -- Increase timeout_ms to give jdtls time to respond
--     vim.lsp.buf.format({
--       timeout_ms = 5000,
--       filter = function(client)
--         return client.name == "intellij"
--       end,
--     })
--   end,
-- })
vim.lsp.enable("jdtls", false)
